name: Generate and Publish Client Libraries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Or your preferred Node.js version
      
      - name: Install Dependencies
        run: npm install
        
      # - name: Validate Schemas
      #   run: node validate-schemas.js # Assuming you have a validation script

      - name: Generate TypeScript Client
        run: node ./clients/typescript/generate.js
        
      - name: Publish TypeScript Client (if on main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          cd clients/typescript
          npm version patch # Increment version (optional)
          npm publish --access public 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
